# Generated by Django 4.0.5 on 2022-06-05 18:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("counter", models.BigIntegerField()),
            ],
        ),
    ]
