# Generated by Django 4.0.5 on 2022-06-06 16:58
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_dog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModifiedDog",
            fields=[
                (
                    "source_dog",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.dog",
                    ),
                ),
                (
                    "modified_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="modified_dogs/"
                    ),
                ),
            ],
        ),
    ]
