# Generated by Django 4.0.5 on 2022-06-06 22:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_dog_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="source_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
